
import com.email.durgesh.Email;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Muhammad Faseeh
 */
public class MakeOrder extends javax.swing.JFrame {
    /**
     * Creates new form MenuList
     */
    public MakeOrder() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        CSQuantityText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ZingerQuantityText = new javax.swing.JTextField();
        CBQuantityText = new javax.swing.JTextField();
        BBQuantityText = new javax.swing.JTextField();
        BQuantityText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ZPrice = new javax.swing.JTextField();
        CBPrice = new javax.swing.JTextField();
        BBPrice = new javax.swing.JTextField();
        BPrice = new javax.swing.JTextField();
        CSPrice = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        CalculateText = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        NameText = new javax.swing.JTextField();
        AddressText = new javax.swing.JTextField();
        PhoneNoText = new javax.swing.JTextField();
        EmailText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        OrderNumber = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("Entered Cash");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HUNGRY FOODIES");
        setLocation(new java.awt.Point(250, 100));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/hungry foodies.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel3);
        jLabel3.setBounds(340, 0, 300, 70);

        CSQuantityText.setText("0");
        CSQuantityText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CBQuantityTextKeyReleased(evt);
            }
        });
        jPanel1.add(CSQuantityText);
        CSQuantityText.setBounds(280, 360, 80, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("5");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 370, 80, 17);

        ZingerQuantityText.setText("0");
        ZingerQuantityText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CBQuantityTextKeyReleased(evt);
            }
        });
        jPanel1.add(ZingerQuantityText);
        ZingerQuantityText.setBounds(280, 200, 80, 30);

        CBQuantityText.setText("0");
        CBQuantityText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CBQuantityTextKeyReleased(evt);
            }
        });
        jPanel1.add(CBQuantityText);
        CBQuantityText.setBounds(280, 240, 80, 30);

        BBQuantityText.setText("0");
        BBQuantityText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CBQuantityTextKeyReleased(evt);
            }
        });
        jPanel1.add(BBQuantityText);
        BBQuantityText.setBounds(280, 280, 80, 30);

        BQuantityText.setText("0");
        BQuantityText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CBQuantityTextKeyReleased(evt);
            }
        });
        jPanel1.add(BQuantityText);
        BQuantityText.setBounds(280, 320, 80, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Price/Per Item");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(370, 170, 150, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Item No");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 170, 80, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("1");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 210, 80, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("2");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 250, 80, 17);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("3");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 290, 80, 17);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("4");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(30, 330, 80, 17);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Quantity");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(280, 170, 100, 20);

        ZPrice.setEditable(false);
        ZPrice.setBackground(new java.awt.Color(255, 255, 255));
        ZPrice.setText("230");
        jPanel1.add(ZPrice);
        ZPrice.setBounds(390, 200, 80, 30);

        CBPrice.setEditable(false);
        CBPrice.setBackground(new java.awt.Color(255, 255, 255));
        CBPrice.setText("200");
        CBPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBPriceActionPerformed(evt);
            }
        });
        jPanel1.add(CBPrice);
        CBPrice.setBounds(390, 240, 80, 30);

        BBPrice.setEditable(false);
        BBPrice.setBackground(new java.awt.Color(255, 255, 255));
        BBPrice.setText("210");
        jPanel1.add(BBPrice);
        BBPrice.setBounds(390, 280, 80, 30);

        BPrice.setEditable(false);
        BPrice.setBackground(new java.awt.Color(255, 255, 255));
        BPrice.setText("230");
        jPanel1.add(BPrice);
        BPrice.setBounds(390, 320, 80, 30);

        CSPrice.setEditable(false);
        CSPrice.setBackground(new java.awt.Color(255, 255, 255));
        CSPrice.setText("250");
        jPanel1.add(CSPrice);
        CSPrice.setBounds(390, 360, 80, 30);

        jButton12.setBackground(new java.awt.Color(153, 153, 153));
        jButton12.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jButton12.setForeground(new java.awt.Color(0, 0, 0));
        jButton12.setText("TOTAL AMOUNT");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12);
        jButton12.setBounds(120, 400, 130, 30);

        CalculateText.setEditable(false);
        CalculateText.setBackground(new java.awt.Color(255, 255, 255));
        CalculateText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateTextActionPerformed(evt);
            }
        });
        jPanel1.add(CalculateText);
        CalculateText.setBounds(280, 400, 190, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Item");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(150, 170, 50, 20);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Clubsandwich");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(110, 360, 150, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Zinger Burger");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(110, 200, 130, 30);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Chicken Burger");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(110, 240, 150, 30);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Beef Burger");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(110, 280, 150, 30);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Broast");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(110, 320, 150, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("ORDER DETAILS");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(160, 110, 200, 27);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Name");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(600, 200, 53, 22);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Address");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(600, 240, 71, 22);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Phone No");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(600, 280, 88, 22);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Email");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(600, 320, 49, 22);
        jPanel1.add(NameText);
        NameText.setBounds(700, 190, 270, 30);
        jPanel1.add(AddressText);
        AddressText.setBounds(700, 230, 270, 30);
        jPanel1.add(PhoneNoText);
        PhoneNoText.setBounds(700, 270, 270, 30);
        jPanel1.add(EmailText);
        EmailText.setBounds(700, 310, 270, 30);

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("MAKE ORDER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(560, 490, 110, 30);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Customer Information");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(610, 110, 248, 27);

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(350, 490, 110, 30);
        jPanel1.add(OrderNumber);
        OrderNumber.setBounds(280, 439, 190, 30);

        jButton3.setBackground(new java.awt.Color(153, 153, 153));
        jButton3.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText(" ORDER NUMBER");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(120, 440, 130, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed

        int value1 = Integer.parseInt(CSQuantityText.getText());
        int value2 = Integer.parseInt(ZingerQuantityText.getText());
        int value3 = Integer.parseInt(BBQuantityText.getText());
        int value4 = Integer.parseInt(CBQuantityText.getText());
        int value5 = Integer.parseInt(BQuantityText.getText());
        int ChickenBurgerPrice = Integer.parseInt(CBPrice.getText());
        int BeefBurgerPrice = Integer.parseInt(BBPrice.getText());
        int ClubSandwichPrice = Integer.parseInt(CSPrice.getText());
        int ZingerBurgerPrice = Integer.parseInt(ZPrice.getText());
        int BroastPrice = Integer.parseInt(BPrice.getText());
        CalculateText.setText(Integer.toString( value1 * ClubSandwichPrice + value2 *ZingerBurgerPrice  + value3 *BeefBurgerPrice + value4 *ChickenBurgerPrice + value5 *BroastPrice));
        
//        int value6 = Integer.parseInt(jTextField1.getText());
        
                
                

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void CalculateTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CalculateTextActionPerformed

    private void CBQuantityTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CBQuantityTextKeyReleased

        // TODO add your handling code here:
        try{
        Integer.parseInt(ZingerQuantityText.getText());   
        }
        catch(Exception e){
            ZingerQuantityText.setText("");
        }
         try{
        Integer.parseInt(BBQuantityText.getText());   
        }
        catch(Exception e){
            BBQuantityText.setText("");
        }
          try{
        Integer.parseInt(CBQuantityText.getText());   
        }
        catch(Exception e){
            CBQuantityText.setText("");
        }
            try{
        Integer.parseInt(CSQuantityText.getText());   
        }
        catch(Exception e){
            CSQuantityText.setText("");
        }
              try{
        Integer.parseInt(BQuantityText.getText());   
        }
        catch(Exception e){
            BQuantityText.setText("");
        }
         
         
            
         

    }//GEN-LAST:event_CBQuantityTextKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here
        Order c=new Order();
         c.setName(NameText.getText());
        c.setP_no(PhoneNoText.getText());
        c.setAddress(AddressText.getText());
        c.setEmail(EmailText.getText());
        c.setTotal(CalculateText.getText());
        c.setOrderNumber(OrderNumber.getText());
        try{
            connect c2=new connect();
            String employee = "insert into ordering values('"+c.getOrderNumber()+"','"+c.getName()+"','"+c.getP_no()+"','"+c.getAddress()+"','"+c.getEmail()+"','"+c.getTotal()+"')";
               c2.s.executeUpdate(employee);
               JOptionPane.showMessageDialog(null,"!! THANKYOU FOR ORDERING !!\n YOU CAN COLLECT YOUR ORDER WITHIN 30 MINUTES");
              NameText.setText("");
               PhoneNoText.setText("");
                AddressText.setText("");
                 EmailText.setText("");
                 CalculateText.setText("");
                 OrderNumber.setText("");
                Email email = new Email("hungryfoodiesproject@gmail.com", "szabist1"); 
            
            email.setFrom("hungryfoodiesproject@gmail.com", "Hungry Foodies");

            email.setSubject("Order Confirmed!");

            email.setContent("Thank you "+ c.getName() +" for ordering your food! Hope you will enjoy our food."+"\n Your Total bill is "+c.getTotal()                    + "<footer>\n <p>Hungry Foodies <br> Address: R-24, North Nazimabad Food Street, Karachi. <br>Phone No: 03320234043</p> "
                    + "<p><a href=\"mailto:hungryfoodiesproject@gmail.com\">HUNGRY FOODIES</a></p>", "text/html");
            
            email.addRecipient(c.getEmail());
            
            email.send();
                  }
        catch (Exception ee) {
                 JOptionPane.showMessageDialog(null,ee);                       
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
        CustomerControls cc=new CustomerControls();
        cc.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
      int min = 1;
      int max = 10000;
        
      //Generate random int value from 50 to 100 
      System.out.println("Random value in int from "+min+" to "+max+ ":");
      int random_int = (int)Math.floor(Math.random()*(max-min+1)+min);
        String number= String.valueOf(random_int);
        Order c=new Order();
       OrderNumber.setText(number);
      
    }//GEN-LAST:event_jButton3ActionPerformed

    private void CBPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBPriceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MakeOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MakeOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MakeOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MakeOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MakeOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressText;
    private javax.swing.JTextField BBPrice;
    private javax.swing.JTextField BBQuantityText;
    private javax.swing.JTextField BPrice;
    private javax.swing.JTextField BQuantityText;
    private javax.swing.JTextField CBPrice;
    private javax.swing.JTextField CBQuantityText;
    private javax.swing.JTextField CSPrice;
    private javax.swing.JTextField CSQuantityText;
    private javax.swing.JTextField CalculateText;
    private javax.swing.JTextField EmailText;
    private javax.swing.JTextField NameText;
    private javax.swing.JTextField OrderNumber;
    private javax.swing.JTextField PhoneNoText;
    private javax.swing.JTextField ZPrice;
    private javax.swing.JTextField ZingerQuantityText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
